openapi: 3.0.0
info:
  title: Experience
  version: '1.0'
  contact:
    name: Sean Gayler
    email: scianciogayl@student.unimelb.edu.au
  description: API for camelCase
servers:
  - url: 'http://localhost:5000'
paths:
  '/api/experience/{userID}':
    parameters:
      - schema:
          type: string
        name: userID
        in: path
        required: true
        description: ID of user
    get:
      summary: Get all experiences of a user
      tags: []
      responses:
        '200':
          description: Successfully retrieved user experiences
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: success
                  data:
                    required:
                      - experiences
                    type: object
                    properties:
                      experiences:
                        type: array
                        items:
                          type: object
                          properties:
                            organisation:
                              type: string
                            jobTitle:
                              type: string
                            description:
                              type: string
                            startDate:
                              type: string
                              format: date
                            endDate:
                              type: string
                              format: date
                            location:
                              type: string
                            experienceID:
                              type: string
                          required:
                            - organisation
                            - jobTitle
                            - description
                            - startDate
                            - endDate
                            - location
                            - experienceID
                required:
                  - status
                  - data
        '401':
          description: 'User has profile set to private, so you cannot view their experiences.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: error
                  message:
                    type: string
                    default: User has profile set to private.
                required:
                  - status
                  - message
        '404':
          description: 'Profile not found, so you cannot view their experiences.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: error
                  message:
                    type: string
                    default: Profile does not exist.
                required:
                  - status
                  - message
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: error
                  message:
                    type: string
                required:
                  - status
                  - message
      operationId: get-api-experience-userID
  /api/experience/getOwnExperiences:
    get:
      summary: Get your own experiences
      tags: []
      responses:
        '200':
          description: Experiences successfully returned.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: success
                  data:
                    type: object
                    required:
                      - experiences
                    properties:
                      experiences:
                        type: array
                        items:
                          type: object
                          properties:
                            organisation:
                              type: string
                            jobTitle:
                              type: string
                            description:
                              type: string
                            startDate:
                              type: string
                              format: date
                            endDate:
                              type: string
                              format: date
                            location:
                              type: string
                            experienceID:
                              type: integer
                          required:
                            - organisation
                            - jobTitle
                            - description
                            - startDate
                            - endDate
                            - location
                            - experienceID
                required:
                  - status
                  - data
        '404':
          description: 'Profile not found, so you cannot get experiences.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: error
                  message:
                    type: string
                    default: Could not find a profile by that ID
                required:
                  - status
                  - message
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: error
                  message:
                    type: string
                required:
                  - status
                  - message
      operationId: get-api-experiences-getOwnExperiences
      description: Retrieves your own experiences. You must be authenticated to use this endpoint.
    parameters: []
  /api/experience:
    delete:
      summary: Delete an experience
      tags: []
      responses:
        '200':
          description: Experience successfully deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: success
                required:
                  - status
        '404':
          description: Profile does not exist or that experience does not exist.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: error
                  message:
                    type: string
                    enum:
                      - Profile does not exist.
                      - The experience you tried to delete does not exist.
                required:
                  - status
                  - message
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: error
                  message:
                    type: string
                required:
                  - status
                  - message
      operationId: delete-api-experience
      description: Deletes an experience. You must be authenticated.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    experienceID:
                      type: integer
    put:
      summary: Update an experience
      tags: []
      responses:
        '200':
          description: Experience succesfully updated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: success
                required:
                  - status
        '404':
          description: Profile was not found or experience does not exist by that ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: error
                  message:
                    type: string
                    enum:
                      - Profile does not exist.
                      - The experience you tried to update does not exist.
                required:
                  - status
                  - message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: error
                  message:
                    type: string
                required:
                  - status
                  - message
      operationId: put-api-experience
      description: Update an existing experience. You must be authenticated.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  required:
                    - experienceID
                  properties:
                    location:
                      type: string
                    organisation:
                      type: string
                    jobTitle:
                      type: string
                    description:
                      type: string
                    startDate:
                      type: string
                      format: date
                    endDate:
                      type: string
                      format: date
                    experienceID:
                      type: integer
              required:
                - data
        description: ''
    post:
      summary: Create a new experience
      tags: []
      responses:
        '200':
          description: Experience successfully added. The expreienceID is returned.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: success
                  data:
                    type: object
                    required:
                      - experienceID
                    properties:
                      experienceID:
                        type: integer
                required:
                  - status
                  - data
        '404':
          description: Profile not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: error
                  message:
                    type: string
                    default: Profile does not exist.
                required:
                  - status
                  - message
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: error
                  message:
                    type: string
                required:
                  - status
                  - message
      operationId: post-api-experience
      description: Create a new experience. You must be authenticated.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  required:
                    - organisation
                    - startDate
                  properties:
                    organisation:
                      type: string
                    jobTitle:
                      type: string
                    description:
                      type: string
                    startDate:
                      type: string
                      format: date
                    endDate:
                      type: string
                      format: date
                    location:
                      type: string
              required:
                - data
components:
  schemas: {}
